
version: 2

models:
  - name: dim_bollinger
    description: "20-day Bollinger bands"
    columns:
      - name: ticker
        description: "Stock symbol"
        tests:
          - not_null

  - name: dim_mfi
    description: "14-day Money Flow Index"
    columns:
      - name: ticker
        description: "Stock symbol"
        tests:
          - not_null
          