version: 2

models:
  - name: dim_organization_overview
    description: "Detailed organization's data"
    tests: 
      - table_column_count:
          model_name: 'dim_organization_overview'
          count: 25
    columns:
      - name: ticker
        description: "Stock symbol of dim_organization_overview, primary key for this table"
        tests:
          - unique
          - not_null
          - invalid_length
          - not_uppercase

  - name: dim_price_history
    description: "Cleaned daily stock price history data"
    columns:
      - name: ticker
        description: "Stock symbols"
        tests:
          - not_null
          - invalid_length
          - not_uppercase
          - relationships:
              to: ref('dim_organization_overview')
              field: ticker

  - name: dim_balance_sheet
    description: "Organization balance sheet report"
    columns:
      - name: ticker
        description: "Stock symbols"
        tests:
          - not_null
          - invalid_length
          - not_uppercase
          - relationships:
              to: ref('dim_organization_overview')
              field: ticker

  - name: dim_cash_flow
    description: "Organization cash flow report"
    columns:
      - name: ticker
        description: "Stock symbols"
        tests:
          - not_null
          - invalid_length
          - not_uppercase
          - relationships:
              to: ref('dim_organization_overview')
              field: ticker

  - name: dim_income_statement
    description: "Organization income statement report"
    columns:
      - name: ticker
        description: "Stock symbols"
        tests:
          - not_null
          - invalid_length
          - not_uppercase
          - relationships:
              to: ref('dim_organization_overview')
              field: ticker

  - name: dim_general_rating
    description: "Organization general stock rating, ranging from 1 to 5"
    columns:
      - name: ticker
        description: "Stock symbols"
        tests:
          - unique
          - not_null
          - invalid_length
          - not_uppercase
          - relationships:
              to: ref('dim_organization_overview')
              field: ticker
